import numpy as np

TEST_CASES_CONSTRUCTOR = [
    (2, 2, False, False, {"bitmask_out": np.asarray([[2, 1]], np.uint8)}),
    (2, 2, False, False, {"bitmask_in": np.asarray([[2, 1]], np.uint8)}),
    (2, 2, False, False, {"adjacency_matrix_colors": np.asarray([[0, 1], [1, 0]], np.uint8)}),
    (2, 2, False, False, {"adjacency_matrix_binary": np.asarray([[[0, 1], [1, 0]]], np.uint8)}),
    (2, 2, False, False, {"flattened_row_major_colors": np.asarray([1], np.uint8)}),
    (2, 2, False, False, {"flattened_row_major_binary": np.asarray([[1]], np.uint8)}),
    (2, 2, False, False, {"flattened_clockwise_colors": np.asarray([1], np.uint8)}),
    (2, 2, False, False, {"flattened_clockwise_binary": np.asarray([[1]], np.uint8)}),
    (2, 2, False, True, {"bitmask_out": np.asarray([[2, 3]], np.uint8)}),
    (2, 2, False, True, {"bitmask_in": np.asarray([[2, 3]], np.uint8)}),
    (2, 2, False, True, {"adjacency_matrix_colors": np.asarray([[0, 1], [1, 1]], np.uint8)}),
    (2, 2, False, True, {"adjacency_matrix_binary": np.asarray([[[0, 1], [1, 1]]], np.uint8)}),
    (2, 2, False, True, {"flattened_row_major_colors": np.asarray([0, 1, 1], np.uint8)}),
    (2, 2, False, True, {"flattened_row_major_binary": np.asarray([[0, 1, 1]], np.uint8)}),
    (2, 2, False, True, {"flattened_clockwise_colors": np.asarray([0, 1, 1], np.uint8)}),
    (2, 2, False, True, {"flattened_clockwise_binary": np.asarray([[0, 1, 1]], np.uint8)}),
    (2, 2, True, False, {"bitmask_out": np.asarray([[2, 0]], np.uint8)}),
    (2, 2, True, False, {"bitmask_in": np.asarray([[0, 1]], np.uint8)}),
    (2, 2, True, False, {"adjacency_matrix_colors": np.asarray([[0, 1], [0, 0]], np.uint8)}),
    (2, 2, True, False, {"adjacency_matrix_binary": np.asarray([[[0, 1], [0, 0]]], np.uint8)}),
    (2, 2, True, False, {"flattened_row_major_colors": np.asarray([1, 0], np.uint8)}),
    (2, 2, True, False, {"flattened_row_major_binary": np.asarray([[1, 0]], np.uint8)}),
    (2, 2, True, False, {"flattened_clockwise_colors": np.asarray([1, 0], np.uint8)}),
    (2, 2, True, False, {"flattened_clockwise_binary": np.asarray([[1, 0]], np.uint8)}),
    (2, 2, True, True, {"bitmask_out": np.asarray([[3, 0]], np.uint8)}),
    (2, 2, True, True, {"bitmask_in": np.asarray([[1, 1]], np.uint8)}),
    (2, 2, True, True, {"adjacency_matrix_colors": np.asarray([[1, 1], [0, 0]], np.uint8)}),
    (2, 2, True, True, {"adjacency_matrix_binary": np.asarray([[[1, 1], [0, 0]]], np.uint8)}),
    (2, 2, True, True, {"flattened_row_major_colors": np.asarray([1, 1, 0, 0], np.uint8)}),
    (2, 2, True, True, {"flattened_row_major_binary": np.asarray([[1, 1, 0, 0]], np.uint8)}),
    (2, 2, True, True, {"flattened_clockwise_colors": np.asarray([1, 1, 0, 0], np.uint8)}),
    (2, 2, True, True, {"flattened_clockwise_binary": np.asarray([[1, 1, 0, 0]], np.uint8)}),
    (2, 3, False, False, {"bitmask_out": np.asarray([[0, 0], [2, 1]], np.uint8)}),
    (2, 3, False, False, {"bitmask_in": np.asarray([[0, 0], [2, 1]], np.uint8)}),
    (2, 3, False, False, {"adjacency_matrix_colors": np.asarray([[0, 2], [2, 0]], np.uint8)}),
    (
        2,
        3,
        False,
        False,
        {"adjacency_matrix_binary": np.asarray([[[0, 0], [0, 0]], [[0, 1], [1, 0]]], np.uint8)},
    ),
    (2, 3, False, False, {"flattened_row_major_colors": np.asarray([2], np.uint8)}),
    (2, 3, False, False, {"flattened_row_major_binary": np.asarray([[0], [1]], np.uint8)}),
    (2, 3, False, False, {"flattened_clockwise_colors": np.asarray([2], np.uint8)}),
    (2, 3, False, False, {"flattened_clockwise_binary": np.asarray([[0], [1]], np.uint8)}),
]
